//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.20 at 04:06:53 AM GMT 
//


package economics.model;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the economics.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _SortOrder_QNAME = new QName("", "sort_order");
    private final static QName _Limit_QNAME = new QName("", "limit");
    private final static QName _RealtimeStart_QNAME = new QName("", "realtime_start");
    private final static QName _FileType_QNAME = new QName("", "file_type");
    private final static QName _OrderBy_QNAME = new QName("", "order_by");
    private final static QName _Units_QNAME = new QName("", "units");
    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _Offset_QNAME = new QName("", "offset");
    private final static QName _OutputType_QNAME = new QName("", "output_type");
    private final static QName _RealtimeEnd_QNAME = new QName("", "realtime_end");
    private final static QName _ObservationEnd_QNAME = new QName("", "observation_end");
    private final static QName _ObservationStart_QNAME = new QName("", "observation_start");
    private final static QName _Count_QNAME = new QName("", "count");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: economics.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link Observations }
     * 
     */
    public Observations createObservations() {
        return new Observations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<Double> createValue(Double value) {
        return new JAXBElement<Double>(_Value_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sort_order")
    public JAXBElement<String> createSortOrder(String value) {
        return new JAXBElement<String>(_SortOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "limit")
    public JAXBElement<BigInteger> createLimit(BigInteger value) {
        return new JAXBElement<BigInteger>(_Limit_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "realtime_start")
    public JAXBElement<XMLGregorianCalendar> createRealtimeStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RealtimeStart_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "file_type")
    public JAXBElement<String> createFileType(String value) {
        return new JAXBElement<String>(_FileType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order_by")
    public JAXBElement<String> createOrderBy(String value) {
        return new JAXBElement<String>(_OrderBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "units")
    public JAXBElement<String> createUnits(String value) {
        return new JAXBElement<String>(_Units_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<XMLGregorianCalendar> createDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Date_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "offset")
    public JAXBElement<BigInteger> createOffset(BigInteger value) {
        return new JAXBElement<BigInteger>(_Offset_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "output_type")
    public JAXBElement<String> createOutputType(String value) {
        return new JAXBElement<String>(_OutputType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "realtime_end")
    public JAXBElement<XMLGregorianCalendar> createRealtimeEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RealtimeEnd_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "observation_end")
    public JAXBElement<XMLGregorianCalendar> createObservationEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ObservationEnd_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "observation_start")
    public JAXBElement<XMLGregorianCalendar> createObservationStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ObservationStart_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "count")
    public JAXBElement<BigInteger> createCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_Count_QNAME, BigInteger.class, null, value);
    }

}
