//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.20 at 04:06:53 AM GMT 
//


package economics.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}realtime_start"/>
 *         &lt;element ref="{}realtime_end"/>
 *         &lt;element ref="{}date"/>
 *         &lt;element ref="{}value"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "realtimeStart",
        "realtimeEnd",
        "date",
        "value"
})
@XmlRootElement(name = "observation")
public class Observation {

    @XmlElement(name = "realtime_start", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar realtimeStart;
    @XmlElement(name = "realtime_end", required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar realtimeEnd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar date;
    @XmlElement(name = "value", required = true)
    private double value;

    public Observation() {
        System.out.println("crap");
    }

    /**
     * Gets the value of the realtimeStart property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getRealtimeStart() {
        return realtimeStart;
    }

    /**
     * Sets the value of the realtimeStart property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setRealtimeStart(XMLGregorianCalendar value) {
        this.realtimeStart = value;
    }

    /**
     * Gets the value of the realtimeEnd property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getRealtimeEnd() {
        return realtimeEnd;
    }

    /**
     * Sets the value of the realtimeEnd property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setRealtimeEnd(XMLGregorianCalendar value) {
        this.realtimeEnd = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the value property.
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     */
    public void setValue(double value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append(getValue()).append(" ").append(getDate());
        return builder.toString();
    }
}
